version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./AuthService/.env

  gateway-service:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE: auth-service:50051

  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - db
    env_file:
      - ./AuthService/.env

  test-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
      target: builder
    depends_on:
      - db
    env_file:
      - ./AuthService/.env


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    env_file:
      - ./AuthService/.env
      
volumes:
  db_data: