// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/gallery.proto

package protogallery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Album messages
type CreateAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbumRequest) Reset() {
	*x = CreateAlbumRequest{}
	mi := &file_proto_gallery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumRequest) ProtoMessage() {}

func (x *CreateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumRequest.ProtoReflect.Descriptor instead.
func (*CreateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAlbumRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlbumRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAlbumRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlbumResponse) Reset() {
	*x = CreateAlbumResponse{}
	mi := &file_proto_gallery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlbumResponse) ProtoMessage() {}

func (x *CreateAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlbumResponse.ProtoReflect.Descriptor instead.
func (*CreateAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAlbumResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAlbumsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsByUserRequest) Reset() {
	*x = GetAlbumsByUserRequest{}
	mi := &file_proto_gallery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsByUserRequest) ProtoMessage() {}

func (x *GetAlbumsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumsByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlbumsByUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAlbumsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albums        []*Album               `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsByUserResponse) Reset() {
	*x = GetAlbumsByUserResponse{}
	mi := &file_proto_gallery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsByUserResponse) ProtoMessage() {}

func (x *GetAlbumsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsByUserResponse.ProtoReflect.Descriptor instead.
func (*GetAlbumsByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlbumsByUserResponse) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

type UpdateAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       uint32                 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlbumRequest) Reset() {
	*x = UpdateAlbumRequest{}
	mi := &file_proto_gallery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlbumRequest) ProtoMessage() {}

func (x *UpdateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlbumRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAlbumRequest) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *UpdateAlbumRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAlbumRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlbumResponse) Reset() {
	*x = UpdateAlbumResponse{}
	mi := &file_proto_gallery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlbumResponse) ProtoMessage() {}

func (x *UpdateAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlbumResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAlbumResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       uint32                 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlbumRequest) Reset() {
	*x = DeleteAlbumRequest{}
	mi := &file_proto_gallery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumRequest) ProtoMessage() {}

func (x *DeleteAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAlbumRequest) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

type DeleteAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlbumResponse) Reset() {
	*x = DeleteAlbumResponse{}
	mi := &file_proto_gallery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlbumResponse) ProtoMessage() {}

func (x *DeleteAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlbumResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAlbumResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPrivateAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       uint32                 `protobuf:"varint,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateAlbumRequest) Reset() {
	*x = GetPrivateAlbumRequest{}
	mi := &file_proto_gallery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateAlbumRequest) ProtoMessage() {}

func (x *GetPrivateAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateAlbumRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{8}
}

func (x *GetPrivateAlbumRequest) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

type GetPrivateAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *Album                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateAlbumResponse) Reset() {
	*x = GetPrivateAlbumResponse{}
	mi := &file_proto_gallery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateAlbumResponse) ProtoMessage() {}

func (x *GetPrivateAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateAlbumResponse.ProtoReflect.Descriptor instead.
func (*GetPrivateAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{9}
}

func (x *GetPrivateAlbumResponse) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

// Media messages
type AddMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AlbumId       uint32                 `protobuf:"varint,2,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	FileData      []byte                 `protobuf:"bytes,3,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMediaRequest) Reset() {
	*x = AddMediaRequest{}
	mi := &file_proto_gallery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMediaRequest) ProtoMessage() {}

func (x *AddMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMediaRequest.ProtoReflect.Descriptor instead.
func (*AddMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{10}
}

func (x *AddMediaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMediaRequest) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *AddMediaRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type AddMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMediaResponse) Reset() {
	*x = AddMediaResponse{}
	mi := &file_proto_gallery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMediaResponse) ProtoMessage() {}

func (x *AddMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMediaResponse.ProtoReflect.Descriptor instead.
func (*AddMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{11}
}

func (x *AddMediaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMediaByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaByUserRequest) Reset() {
	*x = GetMediaByUserRequest{}
	mi := &file_proto_gallery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaByUserRequest) ProtoMessage() {}

func (x *GetMediaByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaByUserRequest.ProtoReflect.Descriptor instead.
func (*GetMediaByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{12}
}

func (x *GetMediaByUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMediaByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaList     []*Media               `protobuf:"bytes,1,rep,name=media_list,json=mediaList,proto3" json:"media_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaByUserResponse) Reset() {
	*x = GetMediaByUserResponse{}
	mi := &file_proto_gallery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaByUserResponse) ProtoMessage() {}

func (x *GetMediaByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaByUserResponse.ProtoReflect.Descriptor instead.
func (*GetMediaByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{13}
}

func (x *GetMediaByUserResponse) GetMediaList() []*Media {
	if x != nil {
		return x.MediaList
	}
	return nil
}

type MarkAsPrivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       uint32                 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsPrivateRequest) Reset() {
	*x = MarkAsPrivateRequest{}
	mi := &file_proto_gallery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsPrivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsPrivateRequest) ProtoMessage() {}

func (x *MarkAsPrivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsPrivateRequest.ProtoReflect.Descriptor instead.
func (*MarkAsPrivateRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{14}
}

func (x *MarkAsPrivateRequest) GetMediaId() uint32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *MarkAsPrivateRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type MarkAsPrivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsPrivateResponse) Reset() {
	*x = MarkAsPrivateResponse{}
	mi := &file_proto_gallery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsPrivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsPrivateResponse) ProtoMessage() {}

func (x *MarkAsPrivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsPrivateResponse.ProtoReflect.Descriptor instead.
func (*MarkAsPrivateResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{15}
}

func (x *MarkAsPrivateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPrivateMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateMediaRequest) Reset() {
	*x = GetPrivateMediaRequest{}
	mi := &file_proto_gallery_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateMediaRequest) ProtoMessage() {}

func (x *GetPrivateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateMediaRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{16}
}

func (x *GetPrivateMediaRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPrivateMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*Media               `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateMediaResponse) Reset() {
	*x = GetPrivateMediaResponse{}
	mi := &file_proto_gallery_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateMediaResponse) ProtoMessage() {}

func (x *GetPrivateMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateMediaResponse.ProtoReflect.Descriptor instead.
func (*GetPrivateMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{17}
}

func (x *GetPrivateMediaResponse) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type DownloadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       uint32                 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadMediaRequest) Reset() {
	*x = DownloadMediaRequest{}
	mi := &file_proto_gallery_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMediaRequest) ProtoMessage() {}

func (x *DownloadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMediaRequest.ProtoReflect.Descriptor instead.
func (*DownloadMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadMediaRequest) GetMediaId() uint32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type DownloadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadMediaResponse) Reset() {
	*x = DownloadMediaResponse{}
	mi := &file_proto_gallery_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMediaResponse) ProtoMessage() {}

func (x *DownloadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMediaResponse.ProtoReflect.Descriptor instead.
func (*DownloadMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{19}
}

func (x *DownloadMediaResponse) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       uint32                 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_proto_gallery_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteMediaRequest) GetMediaId() uint32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_proto_gallery_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteMediaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DetectSimilarMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       uint32                 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectSimilarMediaRequest) Reset() {
	*x = DetectSimilarMediaRequest{}
	mi := &file_proto_gallery_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectSimilarMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectSimilarMediaRequest) ProtoMessage() {}

func (x *DetectSimilarMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectSimilarMediaRequest.ProtoReflect.Descriptor instead.
func (*DetectSimilarMediaRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{22}
}

func (x *DetectSimilarMediaRequest) GetMediaId() uint32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type DetectSimilarMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*Media               `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectSimilarMediaResponse) Reset() {
	*x = DetectSimilarMediaResponse{}
	mi := &file_proto_gallery_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectSimilarMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectSimilarMediaResponse) ProtoMessage() {}

func (x *DetectSimilarMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectSimilarMediaResponse.ProtoReflect.Descriptor instead.
func (*DetectSimilarMediaResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{23}
}

func (x *DetectSimilarMediaResponse) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

// User messages
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_gallery_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{24}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_gallery_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{25}
}

func (x *CreateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// S3 messages
type ListBucketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsRequest) Reset() {
	*x = ListBucketsRequest{}
	mi := &file_proto_gallery_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsRequest) ProtoMessage() {}

func (x *ListBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsRequest.ProtoReflect.Descriptor instead.
func (*ListBucketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{26}
}

type ListBucketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*Bucket              `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsResponse) Reset() {
	*x = ListBucketsResponse{}
	mi := &file_proto_gallery_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsResponse) ProtoMessage() {}

func (x *ListBucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsResponse.ProtoReflect.Descriptor instead.
func (*ListBucketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{27}
}

func (x *ListBucketsResponse) GetBuckets() []*Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type CreateBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketRequest) Reset() {
	*x = CreateBucketRequest{}
	mi := &file_proto_gallery_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketRequest) ProtoMessage() {}

func (x *CreateBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketRequest.ProtoReflect.Descriptor instead.
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{28}
}

func (x *CreateBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type CreateBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBucketResponse) Reset() {
	*x = CreateBucketResponse{}
	mi := &file_proto_gallery_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketResponse) ProtoMessage() {}

func (x *CreateBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketResponse.ProtoReflect.Descriptor instead.
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{29}
}

func (x *CreateBucketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketRequest) Reset() {
	*x = DeleteBucketRequest{}
	mi := &file_proto_gallery_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketRequest) ProtoMessage() {}

func (x *DeleteBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketRequest.ProtoReflect.Descriptor instead.
func (*DeleteBucketRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteBucketRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type DeleteBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBucketResponse) Reset() {
	*x = DeleteBucketResponse{}
	mi := &file_proto_gallery_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBucketResponse) ProtoMessage() {}

func (x *DeleteBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBucketResponse.ProtoReflect.Descriptor instead.
func (*DeleteBucketResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteBucketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFilesInAlbumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesInAlbumRequest) Reset() {
	*x = GetFilesInAlbumRequest{}
	mi := &file_proto_gallery_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesInAlbumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesInAlbumRequest) ProtoMessage() {}

func (x *GetFilesInAlbumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesInAlbumRequest.ProtoReflect.Descriptor instead.
func (*GetFilesInAlbumRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{32}
}

func (x *GetFilesInAlbumRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type GetFilesInAlbumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileNames     []string               `protobuf:"bytes,1,rep,name=file_names,json=fileNames,proto3" json:"file_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesInAlbumResponse) Reset() {
	*x = GetFilesInAlbumResponse{}
	mi := &file_proto_gallery_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesInAlbumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesInAlbumResponse) ProtoMessage() {}

func (x *GetFilesInAlbumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesInAlbumResponse.ProtoReflect.Descriptor instead.
func (*GetFilesInAlbumResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{33}
}

func (x *GetFilesInAlbumResponse) GetFileNames() []string {
	if x != nil {
		return x.FileNames
	}
	return nil
}

type DownloadTempFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BucketName    string                 `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	ObjectName    string                 `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTempFileRequest) Reset() {
	*x = DownloadTempFileRequest{}
	mi := &file_proto_gallery_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTempFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTempFileRequest) ProtoMessage() {}

func (x *DownloadTempFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTempFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadTempFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{34}
}

func (x *DownloadTempFileRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *DownloadTempFileRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

type DownloadTempFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPath     string                 `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTempFileResponse) Reset() {
	*x = DownloadTempFileResponse{}
	mi := &file_proto_gallery_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTempFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTempFileResponse) ProtoMessage() {}

func (x *DownloadTempFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTempFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadTempFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{35}
}

func (x *DownloadTempFileResponse) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

// Data structures
type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId        uint32                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_proto_gallery_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{36}
}

func (x *Album) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Album) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Album) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Album) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AlbumId       uint32                 `protobuf:"varint,3,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	FileSize      uint32                 `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_proto_gallery_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{37}
}

func (x *Media) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Media) GetAlbumId() uint32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

func (x *Media) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type Bucket struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreationDate       string                 `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LocationConstraint string                 `protobuf:"bytes,3,opt,name=location_constraint,json=locationConstraint,proto3" json:"location_constraint,omitempty"`
	ObjectLockConfig   string                 `protobuf:"bytes,4,opt,name=object_lock_config,json=objectLockConfig,proto3" json:"object_lock_config,omitempty"`
	ObjectDelimiter    string                 `protobuf:"bytes,5,opt,name=object_delimiter,json=objectDelimiter,proto3" json:"object_delimiter,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Bucket) Reset() {
	*x = Bucket{}
	mi := &file_proto_gallery_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gallery_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) {
	return file_proto_gallery_proto_rawDescGZIP(), []int{38}
}

func (x *Bucket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bucket) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *Bucket) GetLocationConstraint() string {
	if x != nil {
		return x.LocationConstraint
	}
	return ""
}

func (x *Bucket) GetObjectLockConfig() string {
	if x != nil {
		return x.ObjectLockConfig
	}
	return ""
}

func (x *Bucket) GetObjectDelimiter() string {
	if x != nil {
		return x.ObjectDelimiter
	}
	return ""
}

var File_proto_gallery_proto protoreflect.FileDescriptor

const file_proto_gallery_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gallery.proto\x12\fprotogallery\"c\n" +
	"\x12CreateAlbumRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"/\n" +
	"\x13CreateAlbumResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x16GetAlbumsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"F\n" +
	"\x17GetAlbumsByUserResponse\x12+\n" +
	"\x06albums\x18\x01 \x03(\v2\x13.protogallery.AlbumR\x06albums\"e\n" +
	"\x12UpdateAlbumRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\rR\aalbumId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"/\n" +
	"\x13UpdateAlbumResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"/\n" +
	"\x12DeleteAlbumRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\rR\aalbumId\"/\n" +
	"\x13DeleteAlbumResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\x16GetPrivateAlbumRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\rR\aalbumId\"D\n" +
	"\x17GetPrivateAlbumResponse\x12)\n" +
	"\x05album\x18\x01 \x01(\v2\x13.protogallery.AlbumR\x05album\"]\n" +
	"\x0fAddMediaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\balbum_id\x18\x02 \x01(\rR\aalbumId\x12\x1b\n" +
	"\tfile_data\x18\x03 \x01(\fR\bfileData\",\n" +
	"\x10AddMediaResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x15GetMediaByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"L\n" +
	"\x16GetMediaByUserResponse\x122\n" +
	"\n" +
	"media_list\x18\x01 \x03(\v2\x13.protogallery.MediaR\tmediaList\"C\n" +
	"\x14MarkAsPrivateRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\rR\amediaId\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\"1\n" +
	"\x15MarkAsPrivateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x16GetPrivateMediaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"D\n" +
	"\x17GetPrivateMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x03(\v2\x13.protogallery.MediaR\x05media\"1\n" +
	"\x14DownloadMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\rR\amediaId\"4\n" +
	"\x15DownloadMediaResponse\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\"/\n" +
	"\x12DeleteMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\rR\amediaId\"/\n" +
	"\x13DeleteMediaResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x19DetectSimilarMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\rR\amediaId\"G\n" +
	"\x1aDetectSimilarMediaResponse\x12)\n" +
	"\x05media\x18\x01 \x03(\v2\x13.protogallery.MediaR\x05media\"E\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\".\n" +
	"\x12CreateUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x14\n" +
	"\x12ListBucketsRequest\"E\n" +
	"\x13ListBucketsResponse\x12.\n" +
	"\abuckets\x18\x01 \x03(\v2\x14.protogallery.BucketR\abuckets\"6\n" +
	"\x13CreateBucketRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\"0\n" +
	"\x14CreateBucketResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x13DeleteBucketRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\"0\n" +
	"\x14DeleteBucketResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"9\n" +
	"\x16GetFilesInAlbumRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\"8\n" +
	"\x17GetFilesInAlbumResponse\x12\x1d\n" +
	"\n" +
	"file_names\x18\x01 \x03(\tR\tfileNames\"[\n" +
	"\x17DownloadTempFileRequest\x12\x1f\n" +
	"\vbucket_name\x18\x01 \x01(\tR\n" +
	"bucketName\x12\x1f\n" +
	"\vobject_name\x18\x02 \x01(\tR\n" +
	"objectName\"9\n" +
	"\x18DownloadTempFileResponse\x12\x1d\n" +
	"\n" +
	"local_path\x18\x01 \x01(\tR\tlocalPath\"f\n" +
	"\x05Album\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\rR\x06userId\"c\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\balbum_id\x18\x03 \x01(\rR\aalbumId\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\rR\bfileSize\"\xcb\x01\n" +
	"\x06Bucket\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rcreation_date\x18\x02 \x01(\tR\fcreationDate\x12/\n" +
	"\x13location_constraint\x18\x03 \x01(\tR\x12locationConstraint\x12,\n" +
	"\x12object_lock_config\x18\x04 \x01(\tR\x10objectLockConfig\x12)\n" +
	"\x10object_delimiter\x18\x05 \x01(\tR\x0fobjectDelimiter2\xca\x03\n" +
	"\fAlbumService\x12R\n" +
	"\vCreateAlbum\x12 .protogallery.CreateAlbumRequest\x1a!.protogallery.CreateAlbumResponse\x12^\n" +
	"\x0fGetAlbumsByUser\x12$.protogallery.GetAlbumsByUserRequest\x1a%.protogallery.GetAlbumsByUserResponse\x12R\n" +
	"\vUpdateAlbum\x12 .protogallery.UpdateAlbumRequest\x1a!.protogallery.UpdateAlbumResponse\x12R\n" +
	"\vDeleteAlbum\x12 .protogallery.DeleteAlbumRequest\x1a!.protogallery.DeleteAlbumResponse\x12^\n" +
	"\x0fGetPrivateAlbum\x12$.protogallery.GetPrivateAlbumRequest\x1a%.protogallery.GetPrivateAlbumResponse2\x87\x05\n" +
	"\fMediaService\x12I\n" +
	"\bAddMedia\x12\x1d.protogallery.AddMediaRequest\x1a\x1e.protogallery.AddMediaResponse\x12[\n" +
	"\x0eGetMediaByUser\x12#.protogallery.GetMediaByUserRequest\x1a$.protogallery.GetMediaByUserResponse\x12X\n" +
	"\rMarkAsPrivate\x12\".protogallery.MarkAsPrivateRequest\x1a#.protogallery.MarkAsPrivateResponse\x12^\n" +
	"\x0fGetPrivateMedia\x12$.protogallery.GetPrivateMediaRequest\x1a%.protogallery.GetPrivateMediaResponse\x12X\n" +
	"\rDownloadMedia\x12\".protogallery.DownloadMediaRequest\x1a#.protogallery.DownloadMediaResponse\x12R\n" +
	"\vDeleteMedia\x12 .protogallery.DeleteMediaRequest\x1a!.protogallery.DeleteMediaResponse\x12g\n" +
	"\x12DetectSimilarMedia\x12'.protogallery.DetectSimilarMediaRequest\x1a(.protogallery.DetectSimilarMediaResponse2^\n" +
	"\vUserService\x12O\n" +
	"\n" +
	"CreateUser\x12\x1f.protogallery.CreateUserRequest\x1a .protogallery.CreateUserResponse2\xd0\x03\n" +
	"\tS3Service\x12R\n" +
	"\vListBuckets\x12 .protogallery.ListBucketsRequest\x1a!.protogallery.ListBucketsResponse\x12U\n" +
	"\fCreateBucket\x12!.protogallery.CreateBucketRequest\x1a\".protogallery.CreateBucketResponse\x12U\n" +
	"\fDeleteBucket\x12!.protogallery.DeleteBucketRequest\x1a\".protogallery.DeleteBucketResponse\x12^\n" +
	"\x0fGetFilesInAlbum\x12$.protogallery.GetFilesInAlbumRequest\x1a%.protogallery.GetFilesInAlbumResponse\x12a\n" +
	"\x10DownloadTempFile\x12%.protogallery.DownloadTempFileRequest\x1a&.protogallery.DownloadTempFileResponseB\x15Z\x13/proto;protogalleryb\x06proto3"

var (
	file_proto_gallery_proto_rawDescOnce sync.Once
	file_proto_gallery_proto_rawDescData []byte
)

func file_proto_gallery_proto_rawDescGZIP() []byte {
	file_proto_gallery_proto_rawDescOnce.Do(func() {
		file_proto_gallery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gallery_proto_rawDesc), len(file_proto_gallery_proto_rawDesc)))
	})
	return file_proto_gallery_proto_rawDescData
}

var file_proto_gallery_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_proto_gallery_proto_goTypes = []any{
	(*CreateAlbumRequest)(nil),         // 0: protogallery.CreateAlbumRequest
	(*CreateAlbumResponse)(nil),        // 1: protogallery.CreateAlbumResponse
	(*GetAlbumsByUserRequest)(nil),     // 2: protogallery.GetAlbumsByUserRequest
	(*GetAlbumsByUserResponse)(nil),    // 3: protogallery.GetAlbumsByUserResponse
	(*UpdateAlbumRequest)(nil),         // 4: protogallery.UpdateAlbumRequest
	(*UpdateAlbumResponse)(nil),        // 5: protogallery.UpdateAlbumResponse
	(*DeleteAlbumRequest)(nil),         // 6: protogallery.DeleteAlbumRequest
	(*DeleteAlbumResponse)(nil),        // 7: protogallery.DeleteAlbumResponse
	(*GetPrivateAlbumRequest)(nil),     // 8: protogallery.GetPrivateAlbumRequest
	(*GetPrivateAlbumResponse)(nil),    // 9: protogallery.GetPrivateAlbumResponse
	(*AddMediaRequest)(nil),            // 10: protogallery.AddMediaRequest
	(*AddMediaResponse)(nil),           // 11: protogallery.AddMediaResponse
	(*GetMediaByUserRequest)(nil),      // 12: protogallery.GetMediaByUserRequest
	(*GetMediaByUserResponse)(nil),     // 13: protogallery.GetMediaByUserResponse
	(*MarkAsPrivateRequest)(nil),       // 14: protogallery.MarkAsPrivateRequest
	(*MarkAsPrivateResponse)(nil),      // 15: protogallery.MarkAsPrivateResponse
	(*GetPrivateMediaRequest)(nil),     // 16: protogallery.GetPrivateMediaRequest
	(*GetPrivateMediaResponse)(nil),    // 17: protogallery.GetPrivateMediaResponse
	(*DownloadMediaRequest)(nil),       // 18: protogallery.DownloadMediaRequest
	(*DownloadMediaResponse)(nil),      // 19: protogallery.DownloadMediaResponse
	(*DeleteMediaRequest)(nil),         // 20: protogallery.DeleteMediaRequest
	(*DeleteMediaResponse)(nil),        // 21: protogallery.DeleteMediaResponse
	(*DetectSimilarMediaRequest)(nil),  // 22: protogallery.DetectSimilarMediaRequest
	(*DetectSimilarMediaResponse)(nil), // 23: protogallery.DetectSimilarMediaResponse
	(*CreateUserRequest)(nil),          // 24: protogallery.CreateUserRequest
	(*CreateUserResponse)(nil),         // 25: protogallery.CreateUserResponse
	(*ListBucketsRequest)(nil),         // 26: protogallery.ListBucketsRequest
	(*ListBucketsResponse)(nil),        // 27: protogallery.ListBucketsResponse
	(*CreateBucketRequest)(nil),        // 28: protogallery.CreateBucketRequest
	(*CreateBucketResponse)(nil),       // 29: protogallery.CreateBucketResponse
	(*DeleteBucketRequest)(nil),        // 30: protogallery.DeleteBucketRequest
	(*DeleteBucketResponse)(nil),       // 31: protogallery.DeleteBucketResponse
	(*GetFilesInAlbumRequest)(nil),     // 32: protogallery.GetFilesInAlbumRequest
	(*GetFilesInAlbumResponse)(nil),    // 33: protogallery.GetFilesInAlbumResponse
	(*DownloadTempFileRequest)(nil),    // 34: protogallery.DownloadTempFileRequest
	(*DownloadTempFileResponse)(nil),   // 35: protogallery.DownloadTempFileResponse
	(*Album)(nil),                      // 36: protogallery.Album
	(*Media)(nil),                      // 37: protogallery.Media
	(*Bucket)(nil),                     // 38: protogallery.Bucket
}
var file_proto_gallery_proto_depIdxs = []int32{
	36, // 0: protogallery.GetAlbumsByUserResponse.albums:type_name -> protogallery.Album
	36, // 1: protogallery.GetPrivateAlbumResponse.album:type_name -> protogallery.Album
	37, // 2: protogallery.GetMediaByUserResponse.media_list:type_name -> protogallery.Media
	37, // 3: protogallery.GetPrivateMediaResponse.media:type_name -> protogallery.Media
	37, // 4: protogallery.DetectSimilarMediaResponse.media:type_name -> protogallery.Media
	38, // 5: protogallery.ListBucketsResponse.buckets:type_name -> protogallery.Bucket
	0,  // 6: protogallery.AlbumService.CreateAlbum:input_type -> protogallery.CreateAlbumRequest
	2,  // 7: protogallery.AlbumService.GetAlbumsByUser:input_type -> protogallery.GetAlbumsByUserRequest
	4,  // 8: protogallery.AlbumService.UpdateAlbum:input_type -> protogallery.UpdateAlbumRequest
	6,  // 9: protogallery.AlbumService.DeleteAlbum:input_type -> protogallery.DeleteAlbumRequest
	8,  // 10: protogallery.AlbumService.GetPrivateAlbum:input_type -> protogallery.GetPrivateAlbumRequest
	10, // 11: protogallery.MediaService.AddMedia:input_type -> protogallery.AddMediaRequest
	12, // 12: protogallery.MediaService.GetMediaByUser:input_type -> protogallery.GetMediaByUserRequest
	14, // 13: protogallery.MediaService.MarkAsPrivate:input_type -> protogallery.MarkAsPrivateRequest
	16, // 14: protogallery.MediaService.GetPrivateMedia:input_type -> protogallery.GetPrivateMediaRequest
	18, // 15: protogallery.MediaService.DownloadMedia:input_type -> protogallery.DownloadMediaRequest
	20, // 16: protogallery.MediaService.DeleteMedia:input_type -> protogallery.DeleteMediaRequest
	22, // 17: protogallery.MediaService.DetectSimilarMedia:input_type -> protogallery.DetectSimilarMediaRequest
	24, // 18: protogallery.UserService.CreateUser:input_type -> protogallery.CreateUserRequest
	26, // 19: protogallery.S3Service.ListBuckets:input_type -> protogallery.ListBucketsRequest
	28, // 20: protogallery.S3Service.CreateBucket:input_type -> protogallery.CreateBucketRequest
	30, // 21: protogallery.S3Service.DeleteBucket:input_type -> protogallery.DeleteBucketRequest
	32, // 22: protogallery.S3Service.GetFilesInAlbum:input_type -> protogallery.GetFilesInAlbumRequest
	34, // 23: protogallery.S3Service.DownloadTempFile:input_type -> protogallery.DownloadTempFileRequest
	1,  // 24: protogallery.AlbumService.CreateAlbum:output_type -> protogallery.CreateAlbumResponse
	3,  // 25: protogallery.AlbumService.GetAlbumsByUser:output_type -> protogallery.GetAlbumsByUserResponse
	5,  // 26: protogallery.AlbumService.UpdateAlbum:output_type -> protogallery.UpdateAlbumResponse
	7,  // 27: protogallery.AlbumService.DeleteAlbum:output_type -> protogallery.DeleteAlbumResponse
	9,  // 28: protogallery.AlbumService.GetPrivateAlbum:output_type -> protogallery.GetPrivateAlbumResponse
	11, // 29: protogallery.MediaService.AddMedia:output_type -> protogallery.AddMediaResponse
	13, // 30: protogallery.MediaService.GetMediaByUser:output_type -> protogallery.GetMediaByUserResponse
	15, // 31: protogallery.MediaService.MarkAsPrivate:output_type -> protogallery.MarkAsPrivateResponse
	17, // 32: protogallery.MediaService.GetPrivateMedia:output_type -> protogallery.GetPrivateMediaResponse
	19, // 33: protogallery.MediaService.DownloadMedia:output_type -> protogallery.DownloadMediaResponse
	21, // 34: protogallery.MediaService.DeleteMedia:output_type -> protogallery.DeleteMediaResponse
	23, // 35: protogallery.MediaService.DetectSimilarMedia:output_type -> protogallery.DetectSimilarMediaResponse
	25, // 36: protogallery.UserService.CreateUser:output_type -> protogallery.CreateUserResponse
	27, // 37: protogallery.S3Service.ListBuckets:output_type -> protogallery.ListBucketsResponse
	29, // 38: protogallery.S3Service.CreateBucket:output_type -> protogallery.CreateBucketResponse
	31, // 39: protogallery.S3Service.DeleteBucket:output_type -> protogallery.DeleteBucketResponse
	33, // 40: protogallery.S3Service.GetFilesInAlbum:output_type -> protogallery.GetFilesInAlbumResponse
	35, // 41: protogallery.S3Service.DownloadTempFile:output_type -> protogallery.DownloadTempFileResponse
	24, // [24:42] is the sub-list for method output_type
	6,  // [6:24] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_gallery_proto_init() }
func file_proto_gallery_proto_init() {
	if File_proto_gallery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gallery_proto_rawDesc), len(file_proto_gallery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_gallery_proto_goTypes,
		DependencyIndexes: file_proto_gallery_proto_depIdxs,
		MessageInfos:      file_proto_gallery_proto_msgTypes,
	}.Build()
	File_proto_gallery_proto = out.File
	file_proto_gallery_proto_goTypes = nil
	file_proto_gallery_proto_depIdxs = nil
}
