version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - db
    env_file:
      - .env

  test-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    depends_on:
      - db
    env_file:
      - .env
    command: > 
      sh -c "if [ \"$RUN_TESTS\" = \"true\" ]; then go test -v ./...; else echo 'Tests are skipped.'; fi"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
volumes:
  db_data: